### ISSUE TITLE
Beta Expired

### ISSUE THREAD

**Issue by Ed-Bryce** [williamMillington/warpinator-iOS#5]
The app can no longer be opened and a pop-up shows saying beta expired. The same message is show when attempting to download from the link in the readme

**Comment by hschauhan** [comment]
Please provide access to beta again. This the best application to share between my iPhone and Linux machine.

**Comment by williamMillington** [comment]
I've re-uploaded the beta; please let me know here if you have any difficulty accessing it. 

Apologies for allowing it to expire; I've set reminders and this shouldn't happen again.

**Comment by NotYourAlejandro** [comment]
Hi, this happened again.
